name: Tests

on:
  push:
    branches:
      - main
      - speedreader
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Cache
        uses: Swatinem/rust-cache@a22603398250b864f7190077025cf752307154dc # v2.7.2
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
